<?php
require __DIR__ . '/../../../config/database.php';
require __DIR__ . '/../../../models/deliveryOrderLogModel.php';

// Load PhpSpreadsheet
require_once __DIR__ . '/../../../vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;
use PhpOffice\PhpSpreadsheet\Worksheet\PageSetup;

$logModel = new deliveryOrderLogModel($config);
$results = $logModel->deliveryOrderLogHeaderReport();
$deliveryOrders = [];
foreach ($results as $row) {
    $doCode = $row['do_code'];

    if (!isset($deliveryOrders[$doCode])) {
        $deliveryOrders[$doCode] = [
            'do_code' => $row['do_code'],
            'do_date' => $row['do_date'],
            'status_name' => $row['status_name'],
            'total_qty' => $row['total_qty'] ?? 0,
            'subtotal' => $row['subtotal'],
            'tax_amount' => $row['tax'],
            'grand_total' => $row['total_amount'],
            'items' => []
        ];
    }

    $deliveryOrders[$doCode]['items'][] = [
        'item_name' => $row['item_name'],
        'type' => $row['type'],
        'category' => $row['category'],
        'quantity' => $row['quantity'],
        'unit_price' => $row['unit_price'],
        'line_total' => $row['line_total']
    ];

    if (!isset($deliveryOrders[$doCode]['total_qty']) || $deliveryOrders[$doCode]['total_qty'] == 0) {
        $deliveryOrders[$doCode]['total_qty'] = array_sum(array_column($deliveryOrders[$doCode]['items'], 'quantity'));
    }
}
$deliveryOrders = array_values($deliveryOrders);

// Create new Spreadsheet
$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setTitle('Delivery Orders');

// Set document properties
$spreadsheet->getProperties()
    ->setCreator('Inventory System')
    ->setLastModifiedBy('Inventory System')
    ->setTitle('Delivery Order Report')
    ->setSubject('Delivery Order Report')
    ->setDescription('Delivery Order Report generated by Inventory System')
    ->setKeywords('delivery order report')
    ->setCategory('Report');

// Set page orientation and size
$sheet->getPageSetup()
    ->setOrientation(PageSetup::ORIENTATION_LANDSCAPE)
    ->setPaperSize(PageSetup::PAPERSIZE_A4)
    ->setFitToWidth(1)
    ->setFitToHeight(0);

// Define styles
$headerStyle = [
    'font' => [
        'bold' => true,
        'color' => ['rgb' => 'FFFFFF'],
        'size' => 16
    ],
    'alignment' => [
        'horizontal' => Alignment::HORIZONTAL_CENTER,
        'vertical' => Alignment::VERTICAL_CENTER,
    ],
    'fill' => [
        'fillType' => Fill::FILL_SOLID,
        'startColor' => ['rgb' => '4F81BD']
    ],
    'borders' => [
        'allBorders' => [
            'borderStyle' => Border::BORDER_THIN,
            'color' => ['rgb' => 'FFFFFF']
        ]
    ]
];

$subHeaderStyle = [
    'font' => [
        'bold' => true,
        'size' => 10
    ],
    'alignment' => [
        'horizontal' => Alignment::HORIZONTAL_LEFT,
    ],
    'fill' => [
        'fillType' => Fill::FILL_SOLID,
        'startColor' => ['rgb' => 'E6E6E6']
    ],
    'borders' => [
        'allBorders' => [
            'borderStyle' => Border::BORDER_THIN,
            'color' => ['rgb' => '95B3D7']
        ]
    ]
];

$columnHeaderStyle = [
    'font' => [
        'bold' => true,
        'color' => ['rgb' => 'FFFFFF']
    ],
    'alignment' => [
        'horizontal' => Alignment::HORIZONTAL_CENTER,
        'vertical' => Alignment::VERTICAL_CENTER,
        'wrapText' => true
    ],
    'fill' => [
        'fillType' => Fill::FILL_SOLID,
        'startColor' => ['rgb' => '4F81BD']
    ],
    'borders' => [
        'allBorders' => [
            'borderStyle' => Border::BORDER_THIN,
            'color' => ['rgb' => 'FFFFFF']
        ]
    ]
];

$doHeaderStyle = [
    'font' => [
        'bold' => true
    ],
    'fill' => [
        'fillType' => Fill::FILL_SOLID,
        'startColor' => ['rgb' => 'DCE6F1']
    ],
    'borders' => [
        'allBorders' => [
            'borderStyle' => Border::BORDER_THIN,
            'color' => ['rgb' => '95B3D7']
        ]
    ]
];

$itemRowStyle = [
    'borders' => [
        'allBorders' => [
            'borderStyle' => Border::BORDER_THIN,
            'color' => ['rgb' => '95B3D7']
        ]
    ]
];

$alternateRowStyle = [
    'fill' => [
        'fillType' => Fill::FILL_SOLID,
        'startColor' => ['rgb' => 'F2F2F2']
    ],
    'borders' => [
        'allBorders' => [
            'borderStyle' => Border::BORDER_THIN,
            'color' => ['rgb' => '95B3D7']
        ]
    ]
];

$doTotalStyle = [
    'font' => [
        'bold' => true
    ],
    'fill' => [
        'fillType' => Fill::FILL_SOLID,
        'startColor' => ['rgb' => 'F2F2F2']
    ],
    'alignment' => [
        'horizontal' => Alignment::HORIZONTAL_RIGHT,
    ],
    'borders' => [
        'allBorders' => [
            'borderStyle' => Border::BORDER_THIN,
            'color' => ['rgb' => '95B3D7']
        ]
    ]
];

$summaryStyle = [
    'font' => [
        'bold' => true
    ],
    'fill' => [
        'fillType' => Fill::FILL_SOLID,
        'startColor' => ['rgb' => 'C5D9F1']
    ],
    'borders' => [
        'allBorders' => [
            'borderStyle' => Border::BORDER_THIN,
            'color' => ['rgb' => '95B3D7']
        ]
    ]
];

$currencyStyle = [
    'alignment' => [
        'horizontal' => Alignment::HORIZONTAL_RIGHT,
    ],
    'numberFormat' => [
        'formatCode' => '"Rp" #,##0'
    ],
    'borders' => [
        'allBorders' => [
            'borderStyle' => Border::BORDER_THIN,
            'color' => ['rgb' => '95B3D7']
        ]
    ]
];

// Start row counter
$row = 1;

// Main Report Header
$sheet->mergeCells('A1:I1');
$sheet->setCellValue('A1', 'DELIVERY ORDER REPORT');
$sheet->getStyle('A1')->applyFromArray($headerStyle);
$sheet->getRowDimension(1)->setRowHeight(30);

$row++;

// Sub Header with period info
$sheet->mergeCells('A' . $row . ':I' . $row);
$periodText = 'Period: ' . date('01 M Y') . ' - ' . date('d M Y') . ' | ' .
    'Export Date: ' . date('d/m/Y H:i:s') . ' | ' .
    'Total Orders: ' . count($deliveryOrders);
$sheet->setCellValue('A' . $row, $periodText);
$sheet->getStyle('A' . $row)->applyFromArray($subHeaderStyle);
$sheet->getRowDimension($row)->setRowHeight(20);

$row++;

// Column Headers
$sheet->setCellValue('A' . $row, 'DO Code');
$sheet->setCellValue('B' . $row, 'Date');
$sheet->setCellValue('C' . $row, 'Status');
$sheet->setCellValue('D' . $row, 'Item Name');
$sheet->setCellValue('E' . $row, 'Type');
$sheet->setCellValue('F' . $row, 'Category');
$sheet->setCellValue('G' . $row, 'Qty');
$sheet->setCellValue('H' . $row, 'Unit Price');
$sheet->setCellValue('I' . $row, 'Line Total');

// Set column widths
$sheet->getColumnDimension('A')->setWidth(15);
$sheet->getColumnDimension('B')->setWidth(12);
$sheet->getColumnDimension('C')->setWidth(12);
$sheet->getColumnDimension('D')->setWidth(25);
$sheet->getColumnDimension('E')->setWidth(15);
$sheet->getColumnDimension('F')->setWidth(15);
$sheet->getColumnDimension('G')->setWidth(8);
$sheet->getColumnDimension('H')->setWidth(15);
$sheet->getColumnDimension('I')->setWidth(15);

$sheet->getStyle('A' . $row . ':I' . $row)->applyFromArray($columnHeaderStyle);
$sheet->getRowDimension($row)->setRowHeight(25);

$row++;

// Function to format currency
function formatCurrency($amount)
{
    return 'Rp ' . number_format($amount, 0, ',', '.');
}

// Function to format date
function formatDate($date)
{
    return date('d/m/Y', strtotime($date));
}

// Process each delivery order
foreach ($deliveryOrders as $order) {
    $itemCount = count($order['items']);
    $startRow = $row;

    // DO Header Row
    $sheet->setCellValue('A' . $row, $order['do_code']);
    $sheet->setCellValue('B' . $row, formatDate($order['do_date']));
    $sheet->setCellValue('C' . $row, $order['status_name']);

    $summaryText = 'Items (' . $itemCount . ' items) | Total Qty: ' . $order['total_qty'] . ' | Grand Total: ' . formatCurrency($order['grand_total']);
    $sheet->setCellValue('D' . $row, $summaryText);
    $sheet->mergeCells('D' . $row . ':I' . $row);

    $sheet->getStyle('A' . $row . ':I' . $row)->applyFromArray($doHeaderStyle);

    // Set rowspan for DO header cells (merge vertically)
    if ($itemCount > 0) {
        $sheet->mergeCells('A' . $row . ':A' . ($row + $itemCount));
        $sheet->mergeCells('B' . $row . ':B' . ($row + $itemCount));
        $sheet->mergeCells('C' . $row . ':C' . ($row + $itemCount));

        // Center align the rowspan cells
        $sheet->getStyle('A' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
        $sheet->getStyle('A' . $row)->getAlignment()->setVertical(Alignment::VERTICAL_CENTER);
        $sheet->getStyle('B' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
        $sheet->getStyle('B' . $row)->getAlignment()->setVertical(Alignment::VERTICAL_CENTER);
        $sheet->getStyle('C' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
        $sheet->getStyle('C' . $row)->getAlignment()->setVertical(Alignment::VERTICAL_CENTER);

        // Apply border to merged cells
        $sheet->getStyle('A' . $row . ':A' . ($row + $itemCount))->applyFromArray([
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_THIN,
                    'color' => ['rgb' => '95B3D7']
                ]
            ]
        ]);
        $sheet->getStyle('B' . $row . ':B' . ($row + $itemCount))->applyFromArray([
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_THIN,
                    'color' => ['rgb' => '95B3D7']
                ]
            ]
        ]);
        $sheet->getStyle('C' . $row . ':C' . ($row + $itemCount))->applyFromArray([
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_THIN,
                    'color' => ['rgb' => '95B3D7']
                ]
            ]
        ]);
    }

    $row++;

    // Detail items
    $itemIndex = 0;
    foreach ($order['items'] as $item) {
        $sheet->setCellValue('D' . $row, $item['item_name']);
        $sheet->setCellValue('E' . $row, $item['type']);
        $sheet->setCellValue('F' . $row, $item['category']);
        $sheet->setCellValue('G' . $row, $item['quantity']);
        $sheet->setCellValue('H' . $row, $item['unit_price']);
        $sheet->setCellValue('I' . $row, $item['line_total']);

        // Apply currency format to price columns
        $sheet->getStyle('H' . $row)->getNumberFormat()->setFormatCode('"Rp" #,##0');
        $sheet->getStyle('I' . $row)->getNumberFormat()->setFormatCode('"Rp" #,##0');

        // Apply border to all cells in this row
        $sheet->getStyle('D' . $row . ':I' . $row)->applyFromArray([
            'borders' => [
                'allBorders' => [
                    'borderStyle' => Border::BORDER_THIN,
                    'color' => ['rgb' => '95B3D7']
                ]
            ]
        ]);

        // Apply row style (alternating colors)
        if ($itemIndex % 2 == 0) {
            $sheet->getStyle('D' . $row . ':I' . $row)->applyFromArray($itemRowStyle);
        } else {
            $sheet->getStyle('D' . $row . ':I' . $row)->applyFromArray($alternateRowStyle);
        }

        // Center align quantity
        $sheet->getStyle('G' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

        $itemIndex++;
        $row++;
    }

    // DO Total Row
    $sheet->setCellValue('A' . $row, 'Subtotal:');
    $sheet->setCellValue('B' . $row, 'Tax (10%):');
    $sheet->setCellValue('C' . $row, 'Grand Total:');

    $sheet->setCellValue('D' . $row, formatCurrency($order['subtotal']));
    $sheet->setCellValue('E' . $row, formatCurrency($order['tax_amount']));
    $sheet->setCellValue('F' . $row, formatCurrency($order['grand_total']));

    // Merge and style total row
    $sheet->mergeCells('A' . $row . ':C' . $row);
    $sheet->mergeCells('D' . $row . ':F' . $row);

    $sheet->getStyle('A' . $row . ':F' . $row)->applyFromArray($doTotalStyle);

    // Apply border to merged cells in total row
    $sheet->getStyle('A' . $row . ':C' . $row)->applyFromArray([
        'borders' => [
            'allBorders' => [
                'borderStyle' => Border::BORDER_THIN,
                'color' => ['rgb' => '95B3D7']
            ]
        ]
    ]);
    $sheet->getStyle('D' . $row . ':F' . $row)->applyFromArray([
        'borders' => [
            'allBorders' => [
                'borderStyle' => Border::BORDER_THIN,
                'color' => ['rgb' => '95B3D7']
            ]
        ]
    ]);

    // Apply currency format to total values
    $sheet->getStyle('D' . $row)->getNumberFormat()->setFormatCode('"Rp" #,##0');
    $sheet->getStyle('E' . $row)->getNumberFormat()->setFormatCode('"Rp" #,##0');
    $sheet->getStyle('F' . $row)->getNumberFormat()->setFormatCode('"Rp" #,##0');

    $row++;

    // Empty row as spacer
    $sheet->mergeCells('A' . $row . ':I' . $row);
    $sheet->getRowDimension($row)->setRowHeight(10);
    // Apply border to spacer row
    $sheet->getStyle('A' . $row . ':I' . $row)->applyFromArray([
        'borders' => [
            'top' => [
                'borderStyle' => Border::BORDER_THIN,
                'color' => ['rgb' => '95B3D7']
            ],
            'bottom' => [
                'borderStyle' => Border::BORDER_THIN,
                'color' => ['rgb' => '95B3D7']
            ]
        ]
    ]);
    $row++;
}

// Summary Footer
$totalOrders = count($deliveryOrders);
$totalGrandTotal = array_sum(array_column($deliveryOrders, 'grand_total'));
$totalItems = 0;
foreach ($deliveryOrders as $order) {
    $totalItems += count($order['items']);
}

$sheet->mergeCells('A' . $row . ':I' . $row);
$summaryText = 'Total Orders: ' . $totalOrders . ' | ' .
    'Total Items: ' . $totalItems . ' | ' .
    'Total Revenue: ' . formatCurrency($totalGrandTotal);
$sheet->setCellValue('A' . $row, $summaryText);
$sheet->getStyle('A' . $row)->applyFromArray($summaryStyle);
$sheet->getStyle('A' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

$row += 2;

// Order Summary by Status
$sheet->mergeCells('A' . $row . ':B' . $row);
$sheet->setCellValue('A' . $row, 'ORDER SUMMARY BY STATUS');
$sheet->getStyle('A' . $row)->applyFromArray($columnHeaderStyle);
$sheet->getStyle('A' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
$sheet->getColumnDimension('A')->setAutoSize(true);
$sheet->getColumnDimension('B')->setAutoSize(true);

$row++;

// Calculate summary by status
$statusSummary = [];
foreach ($deliveryOrders as $order) {
    $status = $order['status_name'];
    if (!isset($statusSummary[$status])) {
        $statusSummary[$status] = 0;
    }
    $statusSummary[$status]++;
}

foreach ($statusSummary as $status => $count) {
    $sheet->setCellValue('A' . $row, $status);
    $sheet->setCellValue('B' . $row, $count . ' orders');

    // Apply border to all cells in this row
    $sheet->getStyle('A' . $row . ':B' . $row)->applyFromArray([
        'borders' => [
            'allBorders' => [
                'borderStyle' => Border::BORDER_THIN,
                'color' => ['rgb' => '95B3D7']
            ]
        ]
    ]);

    // Apply alternating row styles
    if ($row % 2 == 0) {
        $sheet->getStyle('A' . $row . ':B' . $row)->applyFromArray($itemRowStyle);
    } else {
        $sheet->getStyle('A' . $row . ':B' . $row)->applyFromArray($alternateRowStyle);
    }

    // Center align count
    $sheet->getStyle('B' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

    $row++;
}

// Apply outer border to main report area
$mainReportLastRow = $row - count($statusSummary) - 3;
if ($mainReportLastRow > 1) {
    $sheet->getStyle('A1:I' . $mainReportLastRow)->applyFromArray([
        'borders' => [
            'outline' => [
                'borderStyle' => Border::BORDER_MEDIUM,
                'color' => ['rgb' => '4F81BD']
            ]
        ]
    ]);
}

// Apply outer border to status summary area
$statusSummaryStartRow = $mainReportLastRow + 2;
$statusSummaryEndRow = $row - 1;
if ($statusSummaryStartRow < $statusSummaryEndRow) {
    $sheet->getStyle('A' . $statusSummaryStartRow . ':B' . $statusSummaryEndRow)->applyFromArray([
        'borders' => [
            'outline' => [
                'borderStyle' => Border::BORDER_MEDIUM,
                'color' => ['rgb' => '4F81BD']
            ]
        ]
    ]);
}

// Set print area
$sheet->getPageSetup()->setPrintArea('A1:I' . ($row - 1));

// Output the file
$filename = 'delivery_order_report_' . date('Ymd_His') . '.xlsx';

header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment;filename="' . $filename . '"');
header('Cache-Control: max-age=0');
header('Pragma: public');

$writer = new Xlsx($spreadsheet);
$writer->save('php://output');
exit;
